### ISSUE TITLE
Web UI instructions and port mapping 

### ISSUE THREAD

**Issue by linuxplayground** [GryBsh/NabuNetworkEmulator#6]
The readme should include instructions on how to access the webui. It's buried in the docker instructions but not explicitly called out anywhere. 

The web port should be configureable. It defaults to 5000 I think but could that be changed in case people are running other workloads on the same host with the same port?

**Comment by GryBsh** [comment]
It's ASP.Net, so you do it the same way as any other asp.net app, by adding a URLs element to the app settings:
```
"Urls": "https://*:5000" <-- the port, hostname, etc
```

**Comment by linuxplayground** [comment]
Awesome. If you add something about this to the readme that should be enough. I'm not sure the nabu community are all that familiar with asp.net. I know I'm not.
